INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '250', 'MIB')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '452', 'MIS')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '251', 'BT')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '453', 'BR')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '464', 'TON2')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '465', 'TON3')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '252', 'CBT')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '454', 'CDA')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '254', 'DR')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '455', 'DA')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '476', 'CM')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '256', 'CCON')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '258', 'CCOV')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '257', 'WCOV')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '261', 'WCON')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '450', 'CCON')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '448', 'MI')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '449', 'PRE')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '459', 'OFL')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '458', 'MSON')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '463', 'TMC')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '457', 'MIMO')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '421', 'PM')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '462', 'RDA')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '470', 'RPM')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '469', 'RMDA')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '264', 'DD')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '265', 'MR1')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '451', 'CFF')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '266', 'FF')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '456', 'EE')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '479', 'EE')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '460', 'OW')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '461', 'OWR')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '466', 'TW')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '467', 'TWR')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '468', 'TWS')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '420', 'ML')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '471', 'MBM')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '42', 'RB')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '95', 'RA')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '31', 'BCV')
INSERT INTO INT100
    (I_INTEGKEY,C_EXTERNALVALUE, C_CISVALUE)
VALUES
    ('25', '96', 'RLD,RL')